name: Windows CI

on: 
  push:
    branches:
      - stable-3.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call the bibletime-win repo
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        repository: bibletime/bibletime-win
        event-type: my-push
        client-payload: '{"ref": "${{ github.ref }}"}'
